CCARE/Models/MasterData/ServiceLevel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using CCARE.Models.MasterData;

namespace CCARE.Models
{
    public class ServiceLevel
    {
        [Key]
        public Guid? ServiceLevelID { get; set; }
        
        [StringLength(200)]
        public string Name { get; set; }

        public Guid? CategoryID { get; set; }

        [StringLength(200)]
        public string CategoryIDName { get; set; }

        public Guid? ProductID { get; set; }

        [StringLength(200)]
        public string ProductIDName { get; set; }
        
        public int SLADays { get; set; }

        public Guid? WorkgroupID { get; set; }

        [StringLength(200)]
        public string WorkgroupIDName { get; set; }
        
        public Guid? CreatedBy { get; set; }

        [StringLength(160)]
        public string CreatedByName { get; set; }

        public DateTime? CreatedOn { get; set; }

        public Guid? ModifiedBy { get; set; }

        [StringLength(160)]
        public string ModifiedByName { get; set; }

        public DateTime? ModifiedOn { get; set; }

        [StringLength(160)]
        public string StateLabel { get; set; }

        public int DeletionStateCode { get; set; }

        public int StateCode { get; set; }

        public int StatusCode { get; set; }

        public Guid? KotaID { get; set; }
        [StringLength(100)]
        public string KotaName { get; set; }

        public Guid? ParentID { get; set; }
        [StringLength(255)]
        public string ParentName { get; set; }

        public Guid? SegmentationID { get; set; }
        [StringLength(200)]
        public string SegmentationName { get; set; }
        [StringLength(500)]
        public string SegmentationDesc { get; set; }
    }
}

CCARE/Models/MasterData/Workflow.cs
//Created by Sumardi
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CCARE.Models.MasterData
{
    public class Workflow
    {
        [Key]
        public Guid ID { get; set; }

		public Guid? SLID { get; set; }
		public Guid? WgID { get; set; }

        [StringLength(200)]
		public string WgName { get; set; }

        public int? WorkflowSLADays { get; set; }
		public int? SeqNo { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
		public DateTime? CreatedOn { get; set; }

		public Guid? CreatedBy { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
		public DateTime? ModifiedOn { get; set; }

		public Guid? ModifiedBy { get; set; }

        [StringLength(500)]
        public string Keterangan { get; set; }
    }
}

CCARE/Controllers/ServiceLevelController.cs
using CCARE.App_Function;
using CCARE.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CCARE.Models.General;
using CCARE.jqGrid;
using System.Configuration;
using CCARE.Models.MasterData;

namespace CCARE.Controllers
{
    public class ServiceLevelController : Controller
    {
        private CRMDb db = new CRMDb();

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult LoadGrid(string sidx, string sord, int rows, int page = 1)
        {
            string getParam = Request["_param"];
            string getVal = Request["_val"];
            string getFilter = Request["_filter"];

            int stateCode = "1".Equals(getFilter) ? 0 : 1;
            var model = db.serviceLevel.Where(x => x.StateCode == stateCode && x.DeletionStateCode == 0);
            int totalRecords = 0;

            if (!string.IsNullOrEmpty(getVal))
            {
                switch (getParam)
                {
                    case "searchSLAName":
                        model = model.Where("(string.IsNullOrEmpty(it.Name) ? string.Empty : it.Name).Contains(@0)", getVal);
                        break;
                    case "searchCategoryName":
                        model = model.Where("(string.IsNullOrEmpty(it.CategoryIDName) ? string.Empty : it.CategoryIDName).Contains(@0)", getVal);
                        break;
                    case "searchProductName":
                        model = model.Where("(string.IsNullOrEmpty(it.ProductIDName) ? string.Empty : it.ProductIDName).Contains(@0)", getVal);
                        break;
                    case "searchSLADays":
                        model = model.Where("(string.IsNullOrEmpty(it.SLADays) ? string.Empty : it.SLADays).Contains(@0)", getVal);
                        break;
                    case "searchWorkGroupName":
                        model = model.Where("(string.IsNullOrEmpty(it.WorkgroupIDName) ? string.Empty : it.WorkgroupIDName).Contains(@0)", getVal);
                        break;
                    case "searchSegmentation":
                        model = model.Where("(string.IsNullOrEmpty(it.SegmentationName) ? string.Empty : it.SegmentationName).Contains(@0)", getVal);
                        break;
                    case "searchKota":
                        model = model.Where("(string.IsNullOrEmpty(it.KotaName) ? string.Empty : it.KotaName).Contains(@0)", getVal);
                        break;
                }
            }
            totalRecords = int.Parse(ConfigurationManager.AppSettings["RecordStaticCount"].ToString());

            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;
            int totalPages = (int)Math.Ceiling((float)totalRecords / (float)pageSize);

            switch (sidx)
            {
                case "Name":
                    model = (sord.ToLower() == "desc") ? model.OrderByDescending(x => x.Name) : model.OrderBy(x => x.Name);
                    break;
                case "CategoryIDName":
                    model = (sord.ToLower() == "desc") ? model.OrderByDescending(x => x.CategoryIDName) : model.OrderBy(x => x.CategoryIDName);
                    break;
                case "ProductIDName":
                    model = (sord.ToLower() == "desc") ? model.OrderByDescending(x => x.ProductIDName) : model.OrderBy(x => x.ProductIDName);
                    break;
                case "SLADays":
                    model = (sord.ToLower() == "desc") ? model.OrderByDescending(x => x.SLADays) : model.OrderBy(x => x.SLADays);
                    break;
                case "WorkgroupIDName":
                    model = (sord.ToLower() == "desc") ? model.OrderByDescending(x => x.WorkgroupIDName) : model.OrderBy(x => x.WorkgroupIDName);
                    break;
                case "CreatedByName":
                    model = (sord.ToLower() == "desc") ? model.OrderByDescending(x => x.CreatedByName) : model.OrderBy(x => x.CreatedByName);
                    break;
                case "CreatedOn":
                    model = (sord.ToLower() == "desc") ? model.OrderByDescending(x => x.CreatedOn) : model.OrderBy(x => x.CreatedOn);
                    break;
                case "ModifiedByName":
                    model = (sord.ToLower() == "desc") ? model.OrderByDescending(x => x.ModifiedByName) : model.OrderBy(x => x.ModifiedByName);
                    break;
                case "ModifiedOn":
                    model = (sord.ToLower() == "desc") ? model.OrderByDescending(x => x.ModifiedOn) : model.OrderBy(x => x.ModifiedOn);
                    break;
                case "StateLabel":
                    model = (sord.ToLower() == "desc") ? model.OrderByDescending(x => x.StateLabel) : model.OrderBy(x => x.StateLabel);
                    break;
                case "SegmentationName":
                    model = (sord.ToLower() == "desc") ? model.OrderByDescending(x => x.SegmentationName) : model.OrderBy(x => x.SegmentationName);
                    break;
                case "KotaName":
                    model = (sord.ToLower() == "desc") ? model.OrderByDescending(x => x.KotaName) : model.OrderBy(x => x.KotaName);
                    break;
                default:
                    model = (sord.ToLower() == "desc") ? model.OrderByDescending(x => x.CreatedOn) : model.OrderBy(x => x.CreatedOn);
                    break;
            }

            if (model.Skip((page - 1) * pageSize).Take(pageSize).Count() == 0)
            {
                page--;
                if (page < 1)
                {
                    page = 1;
                }
            }

            model = model.Skip((page - 1) * pageSize).Take(pageSize);

            var data = model
                .Select(x => new
                {
                    Id = x.ServiceLevelID,
                    Name = x.Name,
                    CategoryId = x.CategoryID,
                    CategoryName = x.CategoryIDName,
                    ProductId = x.ProductID,
                    ProductName = x.ProductIDName,
                    SLADays = x.SLADays,
                    WorkgroupId = x.WorkgroupID,
                    WorkgroupName = x.WorkgroupIDName,
                    CreatedBy = x.CreatedBy,
                    CreatedByName = x.CreatedByName,
                    CreatedOn = x.CreatedOn,
                    ModifiedBy = x.ModifiedBy,
                    ModifiedByName = x.ModifiedByName,
                    ModifiedOn = x.ModifiedOn,
                    StateLabel = x.StateLabel,
                    DeletionStateCode = x.DeletionStateCode,
                    StateCode = x.StateCode,
                    StatusCode = x.StatusCode,
                    ParentID = x.ParentID,
                    SegmentationID = x.SegmentationID,
                    SegmentationName = x.SegmentationName,
                    KotaID = x.KotaID,
                    KotaName = x.KotaName
                });

            if (data.Count() == 0)
            {
                page--;
                if (page < 1)
                {
                    page = 1;
                }
                totalPages = page;
                totalRecords = page * 10 - data.Count();
            }

            JSONTable jTable = new JSONTable();
            jTable.total = totalPages;
            jTable.page = page;
            jTable.records = totalRecords;
            jTable.rows = data.ToArray();

            return Json(jTable, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            ServiceLevel model = new ServiceLevel();
            model.SLADays = 1;

            ViewBag.Kota = new SelectList(db.Kota.Select(x => new { x.ID, x.Name }).Distinct(), "ID", "Name");
            ViewBag.Segmentation = new SelectList(db.Segmentation.Select(x => new { x.ID, x.Name }).Distinct(), "ID", "Name");
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(ServiceLevel model)
        {
            return formSubmit(model, "Create");
        }

        public ActionResult Edit(Guid id)
        {
            ServiceLevel model = db.serviceLevel.Find(id);
            ViewBag.Kota = new SelectList(db.Kota.Select(x => new { x.ID, x.Name }).Distinct(), "ID", "Name");
            ViewBag.Segmentation = new SelectList(db.Segmentation.Select(x => new { x.ID, x.Name }).Distinct(), "ID", "Name");

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ServiceLevel model)
        {
            return formSubmit(model, "Edit");
        }

        [HttpPost]
        public ActionResult ChangeStatus(ServiceLevel model)
        {
            return formSubmit(model, "ChangeStatus");
        }

        [HttpPost]
        public ActionResult Delete(ServiceLevel model)
        {
            return formSubmit(model, "Delete");
        }

        public ActionResult formSubmit(ServiceLevel model, string actionType)
        {
            List<string> errorMessage = new List<string>();
            string successMessage = Resources.ServiceLevel.SLASuccess;
            SessionForSP sessionParam = new SessionForSP();
            sessionParam.OrganizationID = new Guid(Session["OrganizationID"].ToString());

            if (ModelState.IsValid)
            {
                KeyValuePair<int, string> results = new KeyValuePair<int, string>(1, "");
                model.ModifiedBy = new Guid(Session["CurrentUserID"].ToString());

                if (actionType == "Create")
                {
                    int count = db.serviceLevel
                        .Where(x => x.CategoryID == model.CategoryID)
                        .Where(x => x.ProductID == model.ProductID)
                        .Where(x => x.KotaID == model.KotaID)
                        .Where(x => x.SegmentationID == model.SegmentationID)

CCARE/Views/ServiceLevel/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutInquiry.cshtml";
}

@section title
{
    
}

@section mainmenu{ Administration }
@section submenu{ Master Data Application }
@section menu{ Service Level }

<div class="col-lg-9 inquiry_left">
    <div class="input-group">
        <span class="input-group-btn inquiry_dropdown">
            <select id="inquiry_param" class="form-control">
                <option value="searchSLAName">Name</option>
                <option value="searchCategoryName">Category</option>
                <option value="searchProductName">Product</option>
                <option value="searchSLADays">SLA Days</option>
                <option value="searchWorkGroupName">Workgroup</option>
                <option value="searchSegmentation">Segmentation</option>
                <option value="searchKota">Kota</option>
            </select>
        </span>
        <span class="input-group-btn input_space"></span>
        <input type="text" class="form-control" id="inquiry_val">
        <span class="input-group-btn">
            <button id="btn_search" class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
        </span>
    </div>
    </div>
    <div class="col-lg-3 inquiry_right">
    <div class="input-group col-lg-12">
        <span class="inquiry_dropdown">
            <select id="inquiry_filter" class="form-control">
                <option value="1">Active Service Level</option>
                <option value="2">Inactive Service Level</option>
            </select>
        </span>
    </div>
</div>


@section scriptExt{
 
}

CCARE/Views/ServiceLevel/SegmentationList.cshtml
@model CCARE.Models.ServiceLevel

@{
    ViewBag.Title = "Segmentation List: " + Model.Name;
    if (Request.IsAjaxRequest())
    {
        Layout = null;
    }
    else
    {
        Layout = "~/Views/Shared/_LayoutEntity.cshtml";
    }
}

@section title
{
    Segmentation List
}

@section entityLogo
{
    <img class="crm-logo" src="~/assets/images/ico_lrg_112.gif" />
}

@section formTitle
{
    <div class="text_title">
        <h1>Segmentation</h1>
    </div>
}

@section navHeader
{
}

@section footerStatus
{
}

@section sidebarMenu
{
}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 panel panel-default panel_form_parent scroll-y">
            <br />
            <div class="col-sm-12">
                <!-- title 1 -->
                <div class="row form_text">
                    <div class="panel panel-default panel_form_child">
                        
                        <div class="panel-heading">
                            <label class="control-label sv-header">
                                <strong>Segmentation</strong>
                            </label>
                        </div>

                        <br />

                        <div class="panel-body">
                            <form class="form-horizontal">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="divGrid">
                                            <table id="gridTable"></table>
                                            <div id="jqGridPager"></div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    
                    </div>
                </div>
            
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        $('.onlyParent').hide();

        var gridId = "#gridTable";
        var serviceLevelID = '@(Model.ServiceLevelID)';

        var postData = {
            _serviceLevelID: serviceLevelID
        };
        loadJqgrid(postData);


        function loadJqgrid(postData) {
            $.jgrid.gridUnload(gridId);
            var colModels = [
                { label: 'ID', name: 'Id', index: 'Id', key: true, width: 75, hidden: true },
                { label: 'Name', name: 'Name', index: 'Name', width: 350 },
                { label: 'Kota', name: 'KotaName', width: 150 },
                { label: 'SegementationName', name: 'SegmentationName', width: 150 },
                { label: 'SLA', name: 'SLADays', width: 50 },
                { label: 'Workgroup', name: 'WorkgroupName', width: 200 },
            ];;
            var customVal = getCustomVal("");
            var url = '/ServiceLevel/LoadSegmentation';
            $(gridId).jqGrid({
                url: url,
                mtype: "POST",
                datatype: "json",
                postData: postData,
                colModel: colModels,
                shrinkToFit: false,
                width: '100%',
                autowidth: true,
                height: '100%',
                rowNum: customVal.rowNum,
                rowList: [20, 30],
                rownumbers: true,
                pager: $("#jqGridPager"),
                sortname: 'Id',
                viewrecords: true,
                sortorder: "desc",
                loadComplete: function (data) {
                    //Remove total page on footer
                    $("#sp_1_jqGridPager").hide();
                    $("#input_jqGridPager").contents().filter(function () { return this.nodeType == 3; }).remove();
                    $("#input_jqGridPager").prepend("<text>Page  </text>");

                    //Hide First and last on paging
                    $("#first_jqGridPager").hide();
                    $("#last_jqGridPager").hide();

                    // Disabled input page number in jqgrid paging
                    $("#input_jqGridPager").find("input").attr('disabled', 'disabled');

                    /* Remove rm padding from selbox */
                    $(".ui-pg-selbox").removeClass("rm-padding");

                    //Hide records per page
                    //$(".ui-pg-selbox").hide();

                    if (data.rows.length == 0) {
                    //if (data.records == 0) {
                        var emptyText = '';
                        emptyText += '<table class="ui-jqgrid-btable"><tr><td>&nbsp;&nbsp;&nbsp;</td><td><center><h2>No Records Found</h2><center></td></tr></table>';
                        var grid = $(gridId);
                        var container = grid.parents('.ui-jqgrid-view');
                        container.find('.ui-jqgrid-bdiv').children("table").remove();
                        container.find('.ui-jqgrid-bdiv').append(emptyText);
                    }
                },
                jsonreader: {
                    root: "rows", //array containing actual data
                    page: "page", //current page
                    total: "total", //total pages for the query
                    records: "records", //total number of records
                    cell: 'cell',
                    repeatitems: false,
                    id: "Id" //index of the column with the pk in it
                },
                ondblClickRow: function (rowid, iRow, iCol) {
                    @*var data = jQuery("#gridTable").getRowData(rowid);
                    var url = '@Url.Action("Edit", "ServiceLevel")';
                    openWindow(url + '?id=' + rowid);*@
                }
            })
            .navGrid("#jqGridPager", { edit: false, add: false, del: false, search: false });
        }
    });
</script>